@startuml

client -> server : getUserDetail(arg); 호출
activate client
deactivate client
activate server
database db
server <-> db : user 정보 조회
activate db
deactivate db
server -> client : userDetail 전달
activate client
deactivate client
activate another_node
another_node <-> db : user 정보 갱신
activate db
deactivate db
another_node -> server : user 정보 갱신 알림
deactivate another_node
server <-> db : user 정보 조회
activate db
deactivate db
server -> client : 갱신 된 userDetail 푸시
activate client
deactivate client
deactivate server


@enduml